fix workflow: restore negation

diff --git a/.github/workflows/sync-teams.yaml b/.github/workflows/sync-teams.yaml
--- a/.github/workflows/sync-teams.yaml
+++ b/.github/workflows/sync-teams.yaml
@@ -19,9 +19,12 @@ jobs:
       - name: Check for changes to teams.yaml
         id: teams_dirty
         run: |
-          if $(git diff --quiet HEAD^ HEAD admin/teams.yaml); then
+          if ! $(git diff --quiet HEAD^ HEAD admin/teams.yaml); then
             echo "dirty=true" >> $GITHUB_OUTPUT
           fi
+        # NB: the negation of the if-clause above is not a mistake! In Bash,
+        # a return value of 0 is treated as TRUE (because the command succeeded),
+        # and all other values are treated as FALSE. (AKA opposite of Python)
       - uses: scientific-python/sync-teams-action@main
         with:
           token: ${{ secrets.SYNC_TEAMS_TOKEN }}
